### ISSUE TITLE
Missing update functionality

### ISSUE THREAD

**Issue by LuisThein** [DaytonSquareRoots/firebase-db-web-unofficial#1]
Hi, first of all thanks for this plugin!
So far it worked great, but I'm missing the ability to update data of specific child in my Database.

In the official Flutter/Javascript implementations there is an `update` function. If I'm understanding this correctly, the implementation should be very similar to the `set` method. Any Chance you can add this Method?

**Comment by hooperdev** [comment]
Sure thing.

**Comment by hooperdev** [comment]
Just updated the package to v0.0.2, which includes the update function as you requested.
